// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://uuwjuqbjnjgsgpmcducu.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1d2p1cWJqbmpnc2dwbWNkdWN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM1MzMwODYsImV4cCI6MjA0OTEwOTA4Nn0.wkW5QxL30kEEJbUxlB878acEvmCQrKkw2IfJBGXwJzs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);